import Foundation

/// Centralized disclaimer copy. Kept in the domain core so it is versioned, testable,
/// and reused verbatim across every surface (calculators, protocol builder, onboarding,
/// exports). Wording is intentionally "general wellness / personal record-keeping" to
/// stay on the non-regulated side of the FDA medical-device line and Apple's review rules.
///
/// NOTE: This is a first pass to be reviewed against the regulatory research findings
/// (Isabella Cruz advisor doc) before launch.
public enum Disclaimer {
    /// Bump when the acceptance copy materially changes, to re-prompt users for consent.
    /// v3: full Terms of Service + Privacy Policy (LegalDocuments) replace the short text.
    /// v4: contact/notice mechanisms reworded (no email/entity references pre-launch).
    public static let currentVersion = 4

    /// The short, always-visible line for calculator and dosing surfaces.
    public static let calculator = """
    For personal record-keeping only. This tool performs arithmetic on values you enter — \
    it is not medical advice and does not recommend a dose. Verify every calculation \
    independently and consult a licensed healthcare professional.
    """

    /// Shown for research-only compounds (not FDA-approved for human use).
    public static let researchCompound = """
    This substance is not approved by the FDA for human use and is sold for research \
    purposes only. This app makes no safety, efficacy, or dosing claims. Nothing here is \
    medical advice.
    """

    /// The onboarding acceptance summary. The binding documents are the full Terms of
    /// Service and Privacy Policy (LegalDocuments in the app target); this is the plain-
    /// language digest shown above the acceptance toggle.
    public static let onboarding = """
    PinWise is a personal tracking and organization tool. It is not a medical device, \
    does not diagnose or treat any condition, and does not provide medical advice or dosing \
    recommendations. You are responsible for your own health decisions — always consult a \
    qualified healthcare provider. Your records are stored on your device and in any backup \
    or sync you choose to enable; usage analytics may be used to improve the app as described \
    in the Privacy Policy. By continuing you agree to the Terms of Service and Privacy Policy.
    """

    /// Footer stamped onto exported reports.
    public static let exportFooter = """
    Generated by PinWise for personal record-keeping. Not medical advice. \
    Data self-reported by the user.
    """
}
