import Foundation

// The News feature's data contract. The app and the backend agree ONLY on this shape:
// a backend pipeline publishes a `feed.json` matching `NewsFeed`; the app fetches and
// renders it. Editorial rules (enforced in review + testable here): every item is a
// NEUTRAL summary, carries at least one source citation, and carries a disclaimer.
// The app never editorializes or recommends — it informs and links out.
//
// The bundled `sampleJSON` below is regenerated by the iteration-cycle harness in
// `scripts/news-content/` (research → write → verify → validate). See its README for the
// editorial rules every item must satisfy and how to re-run the cycle.

public enum NewsCategory: String, Codable, CaseIterable, Sendable {
    case trialResults = "Trial results"
    case regulatory = "Regulatory"
    case safety = "Safety"
    case newCompound = "New compound"
    case guidance = "Guidance"
    case general = "General"
}

/// A citation backing a news item — the transparency guarantee.
public struct NewsSource: Codable, Hashable, Sendable, Identifiable {
    public enum Kind: String, Codable, Sendable {
        case trial, journal, preprint, regulatory, news
    }
    public var name: String
    public var url: String
    public var kind: Kind
    public var id: String { url }

    public init(name: String, url: String, kind: Kind) {
        self.name = name
        self.url = url
        self.kind = kind
    }
}

/// One curated feed item — a neutral, cited, dated summary.
public struct NewsItem: Codable, Hashable, Sendable, Identifiable {
    public var id: String
    public var headline: String
    public var summary: String
    public var category: NewsCategory
    /// Compounds referenced, for per-compound filtering (e.g. "Retatrutide").
    public var compounds: [String]
    public var sources: [NewsSource]
    /// ISO-8601 timestamp (kept as String to stay portable/Codable without date strategies).
    public var publishedAt: String
    /// Editorial ranking score for the "Popular / Trending" view.
    public var popularity: Int
    /// Drives an opt-in push and a badge (major trial/regulatory/safety events).
    public var isMajorUpdate: Bool
    /// Per-item disclaimer, shown on every card and detail view.
    public var disclaimer: String
    /// Optional lead-image URL the pipeline attaches (e.g. an Open Graph image). Rendered as
    /// an Apple-News-style thumbnail; the card falls back to a branded gradient when nil.
    public var imageURL: String?
    /// Short scannable teaser (≤~100 chars) for list cards; falls back to `summary` when nil.
    public var teaser: String?

    public init(
        id: String, headline: String, summary: String, category: NewsCategory,
        compounds: [String], sources: [NewsSource], publishedAt: String,
        popularity: Int, isMajorUpdate: Bool, disclaimer: String,
        imageURL: String? = nil, teaser: String? = nil
    ) {
        self.id = id; self.headline = headline; self.summary = summary; self.category = category
        self.compounds = compounds; self.sources = sources; self.publishedAt = publishedAt
        self.popularity = popularity; self.isMajorUpdate = isMajorUpdate; self.disclaimer = disclaimer
        self.imageURL = imageURL; self.teaser = teaser
    }

    /// Text for list/summary contexts: the teaser when present, else the full summary.
    public var listText: String { teaser ?? summary }
}

/// The published feed document the app fetches.
public struct NewsFeed: Codable, Hashable, Sendable {
    public var version: Int
    public var generatedAt: String
    public var items: [NewsItem]

    public init(version: Int, generatedAt: String, items: [NewsItem]) {
        self.version = version; self.generatedAt = generatedAt; self.items = items
    }

    /// "Popular" view — items ranked by editorial score, high to low.
    public var trending: [NewsItem] { items.sorted { $0.popularity > $1.popularity } }

    /// Items mentioning a given compound (for the per-compound news filter).
    public func items(mentioning compound: String) -> [NewsItem] {
        items.filter { $0.compounds.contains(compound) }
    }

    /// Major updates only (push / badges).
    public var majorUpdates: [NewsItem] { items.filter(\.isMajorUpdate) }
}

public extension NewsFeed {
    /// A realistic seed feed — bundled for previews/offline first-launch and used as the
    /// decode fixture that validates the contract. Content mirrors the verified research
    /// gathered via ClinicalTrials.gov, PubMed, and FDA sources (see scripts/news-content/).
    /// Every item is neutral, dated, carries ≥1 real source citation, a disclaimer, and a
    /// ≤100-char teaser; investigational/unapproved status is stated wherever it applies.
    static let sampleJSON: String = #"""
    {
      "version": 1,
      "generatedAt": "2026-07-09T12:00:00Z",
      "items": [
        {
          "id": "fda-bpc157-pcac-2026-07",
          "headline": "FDA panel to review BPC-157 compounding",
          "summary": "The FDA treats BPC-157 as a bulk drug substance that 'may present significant safety risks,' keeping its compounding outside the agency's enforcement discretion. Its Pharmacy Compounding Advisory Committee is scheduled to meet July 23–24, 2026 to evaluate several nominated peptides, including BPC-157, Semax, and epitalon. None of these peptides is FDA-approved.",
          "category": "Regulatory",
          "compounds": ["BPC-157", "Semax", "Epithalon"],
          "sources": [
            {"name": "U.S. FDA — bulk substances that may present significant safety risks", "url": "https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks", "kind": "regulatory"},
            {"name": "U.S. FDA — July 23–24, 2026 Pharmacy Compounding Advisory Committee", "url": "https://www.fda.gov/advisory-committees/advisory-committee-calendar/july-23-24-2026-meeting-pharmacy-compounding-advisory-committee-07232026", "kind": "regulatory"}
          ],
          "publishedAt": "2026-07-09T00:00:00Z",
          "teaser": "FDA's compounding advisory committee meets July 23–24, 2026 to weigh BPC-157 and other peptides.",
          "popularity": 98,
          "isMajorUpdate": true,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "reta-phase2-obesity-2023",
          "headline": "Retatrutide drove ~24% weight loss in Phase 2",
          "summary": "In a 48-week Phase 2 trial of 338 adults with obesity (NEJM 2023), retatrutide at the highest dose (12 mg weekly) produced a mean body-weight reduction of about 24% versus roughly 2% on placebo; gastrointestinal effects were the most common side effects and were mostly mild to moderate. Retatrutide (LY3437943) is an investigational GIP/GLP-1/glucagon triple agonist and is not FDA-approved.",
          "category": "Trial results",
          "compounds": ["Retatrutide"],
          "sources": [
            {"name": "NEJM 2023 (Jastreboff et al., retatrutide Phase 2)", "url": "https://doi.org/10.1056/NEJMoa2301972", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT04881760", "url": "https://clinicaltrials.gov/study/NCT04881760", "kind": "trial"}
          ],
          "publishedAt": "2023-06-26T00:00:00Z",
          "teaser": "Phase 2: up to ~24% mean weight loss at 48 weeks. Still investigational.",
          "popularity": 96,
          "isMajorUpdate": true,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "sema-select-cv-2024",
          "headline": "FDA clears Wegovy to cut heart-attack, stroke risk",
          "summary": "In March 2024 the FDA approved Wegovy (semaglutide 2.4 mg) to reduce the risk of major cardiovascular events in adults with cardiovascular disease and overweight or obesity — the first weight-management drug cleared for cardiovascular risk reduction. It was based on the SELECT trial of 17,604 people without diabetes, where the primary composite occurred in 6.5% on semaglutide versus 8.0% on placebo (about a 20% relative reduction). The approval applies to the branded product, not compounded semaglutide.",
          "category": "Regulatory",
          "compounds": ["Semaglutide"],
          "sources": [
            {"name": "U.S. FDA (press announcement, Mar 2024)", "url": "https://www.fda.gov/news-events/press-announcements/fda-approves-first-treatment-reduce-risk-serious-heart-problems-specifically-adults-obesity-or", "kind": "regulatory"},
            {"name": "NEJM 2023 (Lincoff et al., SELECT)", "url": "https://doi.org/10.1056/NEJMoa2307563", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT03574597", "url": "https://clinicaltrials.gov/study/NCT03574597", "kind": "trial"}
          ],
          "publishedAt": "2024-03-08T00:00:00Z",
          "teaser": "First weight-loss drug FDA-cleared to lower cardiovascular risk (SELECT: ~20% fewer events).",
          "popularity": 95,
          "isMajorUpdate": true,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "tirz-osa-approval-2024",
          "headline": "Zepbound is first drug approved for sleep apnea",
          "summary": "In December 2024 the FDA approved Zepbound (tirzepatide) for moderate-to-severe obstructive sleep apnea in adults with obesity — the first medication ever approved for OSA. In the two SURMOUNT-OSA trials, tirzepatide lowered the apnea–hypopnea index by roughly 25–29 events per hour versus about 5 with placebo over 52 weeks. It is approved as an adjunct to a reduced-calorie diet and activity, not as a replacement for CPAP.",
          "category": "Regulatory",
          "compounds": ["Tirzepatide"],
          "sources": [
            {"name": "U.S. FDA (press announcement, Dec 2024)", "url": "https://www.fda.gov/news-events/press-announcements/fda-approves-first-medication-obstructive-sleep-apnea", "kind": "regulatory"},
            {"name": "NEJM 2024 (Malhotra et al., SURMOUNT-OSA)", "url": "https://doi.org/10.1056/NEJMoa2404881", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT05412004", "url": "https://clinicaltrials.gov/study/NCT05412004", "kind": "trial"}
          ],
          "publishedAt": "2024-12-20T00:00:00Z",
          "teaser": "FDA approves tirzepatide as the first-ever medication for obstructive sleep apnea.",
          "popularity": 93,
          "isMajorUpdate": true,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "sema-oral-pill-2025",
          "headline": "FDA approves first oral GLP-1 pill for weight loss",
          "summary": "In December 2025 the FDA approved an oral form of Wegovy (once-daily semaglutide 25 mg tablet), the first oral GLP-1 receptor agonist approved for weight management. In the OASIS program the pill produced roughly 14–17% average weight loss versus about 2–3% for placebo, and its label also covers cardiovascular risk reduction in adults with established cardiovascular disease. It is the same active drug as injectable Wegovy in a new oral form.",
          "category": "New compound",
          "compounds": ["Semaglutide"],
          "sources": [
            {"name": "Novo Nordisk / PR Newswire (approval announcement, Dec 2025)", "url": "https://www.prnewswire.com/news-releases/fda-approves-novo-nordisks-wegovy-pill-the-first-and-only-oral-glp-1-for-weight-loss-in-adults-302648344.html", "kind": "news"},
            {"name": "AJMC (oral semaglutide approval coverage)", "url": "https://www.ajmc.com/view/fda-approves-oral-semaglutide-as-first-glp-1-pill-for-weight-loss", "kind": "news"}
          ],
          "publishedAt": "2025-12-22T00:00:00Z",
          "teaser": "First oral GLP-1 pill for weight loss is FDA-approved (~14–17% average loss in trials).",
          "popularity": 90,
          "isMajorUpdate": true,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "orforglipron-approval-2026",
          "headline": "FDA approves oral GLP-1 orforglipron (Foundayo)",
          "summary": "On April 1, 2026 the FDA approved orforglipron (brand name Foundayo), a once-daily oral GLP-1 receptor agonist, for chronic weight management in adults with obesity or overweight with a weight-related condition. In the Phase 3 ATTAIN-1 trial the 36 mg dose produced about 11% mean weight loss versus roughly 2% on placebo. A separate type 2 diabetes indication remained under FDA review.",
          "category": "Regulatory",
          "compounds": ["Orforglipron"],
          "sources": [
            {"name": "Eli Lilly investor release (Foundayo FDA approval)", "url": "https://investor.lilly.com/news-releases/news-release-details/fda-approves-lillys-foundayotm-orforglipron-only-glp-1-pill", "kind": "regulatory"},
            {"name": "NEJM 2025 (Wharton et al., ATTAIN-1)", "url": "https://doi.org/10.1056/NEJMoa2511774", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT05869903", "url": "https://clinicaltrials.gov/study/NCT05869903", "kind": "trial"}
          ],
          "publishedAt": "2026-04-01T00:00:00Z",
          "teaser": "Orforglipron, a once-daily oral GLP-1 pill, wins FDA approval for weight management.",
          "popularity": 88,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "sema-mash-essence-2025",
          "headline": "Wegovy wins accelerated approval for MASH",
          "summary": "In 2025 the FDA granted accelerated approval to Wegovy (semaglutide 2.4 mg) for adults with noncirrhotic MASH (metabolic dysfunction-associated steatohepatitis) and moderate-to-advanced liver fibrosis — the first GLP-1 approved for the condition. In the Phase 3 ESSENCE trial, steatohepatitis resolved without worsening fibrosis in about 63% on semaglutide versus 34% on placebo at 72 weeks. As an accelerated approval, continued approval depends on confirmatory outcome data.",
          "category": "Regulatory",
          "compounds": ["Semaglutide"],
          "sources": [
            {"name": "U.S. FDA (drug news, 2025)", "url": "https://www.fda.gov/drugs/news-events-human-drugs/fda-approves-treatment-serious-liver-disease-known-mash", "kind": "regulatory"},
            {"name": "NEJM 2025 (Sanyal et al., ESSENCE part 1)", "url": "https://doi.org/10.1056/NEJMoa2413258", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT04822181", "url": "https://clinicaltrials.gov/study/NCT04822181", "kind": "trial"}
          ],
          "publishedAt": "2025-08-15T00:00:00Z",
          "teaser": "Semaglutide becomes the first GLP-1 approved for the liver disease MASH (ESSENCE).",
          "popularity": 86,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "cagrisema-redefine1-2025",
          "headline": "CagriSema cut weight ~20% in Phase 3",
          "summary": "In the 68-week Phase 3 REDEFINE 1 trial of 3,417 adults with overweight or obesity and without diabetes (NEJM 2025), once-weekly CagriSema — cagrilintide plus semaglutide — reduced body weight by an estimated 20.4% versus 3.0% with placebo. Gastrointestinal effects were common and mostly mild to moderate. CagriSema is investigational and not FDA-approved.",
          "category": "Trial results",
          "compounds": ["Cagrilintide", "Semaglutide"],
          "sources": [
            {"name": "NEJM 2025 (Garvey et al., REDEFINE 1)", "url": "https://doi.org/10.1056/NEJMoa2502081", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT05567796", "url": "https://clinicaltrials.gov/study/NCT05567796", "kind": "trial"}
          ],
          "publishedAt": "2025-06-22T00:00:00Z",
          "teaser": "REDEFINE 1: CagriSema drove ~20% mean weight loss vs 3% on placebo. Investigational.",
          "popularity": 84,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "tirz-summit-hfpef-2024",
          "headline": "Tirzepatide cut events in obesity-related HFpEF",
          "summary": "In the Phase 3 SUMMIT trial (NEJM 2024) of 731 patients with heart failure with preserved ejection fraction and obesity, a composite of cardiovascular death or worsening heart failure occurred in 9.9% on tirzepatide versus 15.3% on placebo, with better patient-reported health status. This is trial evidence for a specific population; check the current label before assuming an approved heart-failure indication.",
          "category": "Trial results",
          "compounds": ["Tirzepatide"],
          "sources": [
            {"name": "NEJM 2024 (Packer et al., SUMMIT)", "url": "https://doi.org/10.1056/NEJMoa2410027", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT04847557", "url": "https://clinicaltrials.gov/study/NCT04847557", "kind": "trial"}
          ],
          "publishedAt": "2024-11-16T00:00:00Z",
          "teaser": "SUMMIT: tirzepatide lowered CV-death/worsening-HF risk in obesity-related HFpEF.",
          "popularity": 82,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "sema-flow-kidney-2024",
          "headline": "Semaglutide slowed kidney disease in FLOW trial",
          "summary": "The Phase 3 FLOW trial (NEJM 2024) of 3,533 people with type 2 diabetes and chronic kidney disease found semaglutide reduced the risk of major kidney outcomes by about 24% versus placebo, and all-cause death by about 20%; the trial was stopped early for efficacy. FLOW used the 1.0 mg diabetes dose, not the higher obesity dose.",
          "category": "Trial results",
          "compounds": ["Semaglutide"],
          "sources": [
            {"name": "NEJM 2024 (Perkovic et al., FLOW)", "url": "https://doi.org/10.1056/NEJMoa2403347", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT03819153", "url": "https://clinicaltrials.gov/study/NCT03819153", "kind": "trial"}
          ],
          "publishedAt": "2024-05-24T00:00:00Z",
          "teaser": "FLOW: semaglutide cut major kidney-disease events ~24% in type 2 diabetes with CKD.",
          "popularity": 80,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "survodutide-mash-ph2-2024",
          "headline": "Survodutide improved MASH in Phase 2",
          "summary": "In a 48-week Phase 2 trial (NEJM 2024) of 293 adults with biopsy-confirmed MASH and fibrosis, MASH improved without worsening fibrosis in roughly 47–62% of survodutide-treated participants (by dose) versus 14% on placebo; nausea, diarrhea and vomiting were more frequent on the drug. Survodutide (BI 456906) is an investigational glucagon/GLP-1 dual agonist and is not FDA-approved.",
          "category": "Trial results",
          "compounds": ["Survodutide"],
          "sources": [
            {"name": "NEJM 2024 (Sanyal et al., survodutide Phase 2 MASH)", "url": "https://doi.org/10.1056/NEJMoa2401755", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT04771273", "url": "https://clinicaltrials.gov/study/NCT04771273", "kind": "trial"}
          ],
          "publishedAt": "2024-06-07T00:00:00Z",
          "teaser": "Phase 2: up to 62% had MASH improvement vs 14% on placebo. Investigational.",
          "popularity": 78,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "mazdutide-glory1-2025",
          "headline": "Mazdutide drove ~14% weight loss in China Phase 3",
          "summary": "In the Phase 3 GLORY-1 trial (NEJM 2025) of 610 Chinese adults with overweight or obesity, 48 weeks of once-weekly mazdutide reduced body weight by a mean of about 14% (6 mg) versus a slight gain on placebo; gastrointestinal effects were most common and mostly mild to moderate. Mazdutide, a GLP-1/glucagon dual agonist, is not FDA-approved.",
          "category": "Trial results",
          "compounds": ["Mazdutide"],
          "sources": [
            {"name": "NEJM 2025 (Ji et al., mazdutide GLORY-1)", "url": "https://doi.org/10.1056/NEJMoa2411528", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT05607680", "url": "https://clinicaltrials.gov/study/NCT05607680", "kind": "trial"}
          ],
          "publishedAt": "2025-05-25T00:00:00Z",
          "teaser": "GLORY-1: mazdutide produced ~14% mean weight loss at 48 weeks. Not FDA-approved.",
          "popularity": 76,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "tesamorelin-visceral-fat-2007",
          "headline": "Tesamorelin cut visceral fat in pivotal HIV trial",
          "summary": "In a 412-patient, 26-week randomized trial (NEJM 2007), the GHRH analog tesamorelin reduced visceral abdominal fat by about 15% versus a small increase on placebo and raised IGF-1, while improving lipids. This trial supported tesamorelin's later FDA approval (as Egrifta, 2010) specifically for excess abdominal fat in HIV-associated lipodystrophy — not for general fat loss or anti-aging.",
          "category": "Trial results",
          "compounds": ["Tesamorelin"],
          "sources": [
            {"name": "NEJM 2007 (Falutz et al.)", "url": "https://doi.org/10.1056/NEJMoa072375", "kind": "journal"},
            {"name": "PubMed 18057338", "url": "https://pubmed.ncbi.nlm.nih.gov/18057338/", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT00123253", "url": "https://clinicaltrials.gov/study/NCT00123253", "kind": "trial"}
          ],
          "publishedAt": "2007-12-06T00:00:00Z",
          "teaser": "Pivotal HIV trial: tesamorelin dropped visceral fat ~15% over 26 weeks.",
          "popularity": 72,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "bpc157-evidence-review-2026",
          "headline": "BPC-157's human evidence stays thin",
          "summary": "A 2026 narrative review in Pharmaceutics (MDPI) concluded that despite 30+ years of mostly rodent research, BPC-157 has no approved formulation, no validated dosing, and no completed Phase II trial, with all human data drawn from fewer than 30 subjects across small uncontrolled studies. BPC-157 is not FDA-approved and remains investigational.",
          "category": "General",
          "compounds": ["BPC-157"],
          "sources": [
            {"name": "Pharmaceutics 2026 (MDPI, doi:10.3390/pharmaceutics18050625)", "url": "https://doi.org/10.3390/pharmaceutics18050625", "kind": "journal"},
            {"name": "Pharmaceuticals (Basel) 2026 review (doi:10.3390/ph19020309)", "url": "https://doi.org/10.3390/ph19020309", "kind": "journal"}
          ],
          "publishedAt": "2026-05-20T00:00:00Z",
          "teaser": "2026 review: no completed Phase II trial; human data from fewer than 30 subjects.",
          "popularity": 70,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "pt141-vyleesi-approval",
          "headline": "PT-141 (Vyleesi) is approved only for low desire",
          "summary": "Bremelanotide (Vyleesi), the melanocortin agonist sold in peptide circles as PT-141, is FDA-approved (2019) only for acquired, generalized hypoactive sexual desire disorder in premenopausal women. In the Phase 3 RECONNECT trials it produced statistically significant but modest improvements in desire, with nausea, flushing and headache common. It is not approved for men, for postmenopausal women, or for tanning or general 'libido' use.",
          "category": "Regulatory",
          "compounds": ["PT-141"],
          "sources": [
            {"name": "FDA Drugs@FDA — Vyleesi (bremelanotide) NDA 210557", "url": "https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=210557", "kind": "regulatory"},
            {"name": "Obstet Gynecol 2019 (Kingsberg et al., RECONNECT)", "url": "https://doi.org/10.1097/AOG.0000000000003500", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT02333071", "url": "https://clinicaltrials.gov/study/NCT02333071", "kind": "trial"}
          ],
          "publishedAt": "2019-06-21T00:00:00Z",
          "teaser": "PT-141/Vyleesi is FDA-approved only for low sexual desire in premenopausal women.",
          "popularity": 68,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "thymosin-alpha1-global-2023",
          "headline": "Thymosin alpha-1: approved abroad, mixed COVID data",
          "summary": "Thymosin alpha-1 (thymalfasin, brand Zadaxin) is an immunomodulator approved in some countries outside the US for chronic hepatitis B and as an adjuvant, but it is not FDA-approved. Meta-analyses of its use in COVID-19 conflict — a 2023 review reported lower mortality in more severe patients, while a 2022 meta-analysis of 5,352 patients found no overall mortality benefit. Both call for randomized trials.",
          "category": "Trial results",
          "compounds": ["Thymosin Alpha-1"],
          "sources": [
            {"name": "Inflammopharmacology 2023 (Soeroto et al., meta-analysis)", "url": "https://doi.org/10.1007/s10787-023-01354-2", "kind": "journal"},
            {"name": "Int Immunopharmacol 2022 (Shang et al., meta-analysis)", "url": "https://doi.org/10.1016/j.intimp.2022.109584", "kind": "journal"}
          ],
          "publishedAt": "2023-10-16T00:00:00Z",
          "teaser": "Approved abroad for hepatitis B; COVID-19 meta-analyses reach opposite conclusions.",
          "popularity": 66,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "thymosin-beta4-eyedrops",
          "headline": "Thymosin beta-4 eye drops reached Phase 3",
          "summary": "Full-length thymosin beta-4, formulated as an ophthalmic solution (RGN-259), has completed Phase 2/3 trials for dry-eye disease and is in Phase 3 for neurotrophic keratopathy — making it the most clinically studied peptide in this group. Injectable cardiac programs were withdrawn before enrolling. Despite this, thymosin beta-4 holds no FDA approval, and the studied product is an eye drop, not the injectable TB-500 fragment.",
          "category": "Trial results",
          "compounds": ["Thymosin Beta-4", "TB-500"],
          "sources": [
            {"name": "ClinicalTrials.gov NCT03937882 (RGN-259, dry eye, Phase 3)", "url": "https://clinicaltrials.gov/study/NCT03937882", "kind": "trial"},
            {"name": "ClinicalTrials.gov NCT05555589 (RGN-259, neurotrophic keratopathy, Phase 3)", "url": "https://clinicaltrials.gov/study/NCT05555589", "kind": "trial"}
          ],
          "publishedAt": "2020-11-08T00:00:00Z",
          "teaser": "Thymosin beta-4 eye drops reached Phase 3 — but the peptide is still unapproved.",
          "popularity": 64,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "gh-secretagogues-evidence",
          "headline": "GH secretagogues raise IGF-1; outcomes unproven",
          "summary": "Across the growth-hormone peptides, human evidence for body-composition or anti-aging benefit stays limited. Only tesamorelin (Egrifta) is FDA-approved, and only for HIV-associated lipodystrophy; sermorelin (Geref) was formerly approved but withdrawn from the US market for commercial reasons, and CJC-1295, ipamorelin and MK-677 have never been approved. Trials consistently show these agents raise GH/IGF-1, but patient-relevant outcomes like strength and function are largely unproven or negative.",
          "category": "General",
          "compounds": ["Tesamorelin", "Sermorelin", "CJC-1295 (DAC)", "CJC-1295 (no DAC)", "Ipamorelin", "MK-677"],
          "sources": [
            {"name": "Ann Intern Med 2008 (Nass et al., MK-677)", "url": "https://doi.org/10.7326/0003-4819-149-9-200811040-00003", "kind": "journal"},
            {"name": "JCEM 2006 (Teichman et al., CJC-1295)", "url": "https://doi.org/10.1210/jc.2005-1536", "kind": "journal"},
            {"name": "Neurology 2008 (Sevigny et al., negative MK-677 AD trial)", "url": "https://doi.org/10.1212/01.wnl.0000335163.88054.e7", "kind": "journal"}
          ],
          "publishedAt": "2008-11-04T00:00:00Z",
          "teaser": "Only tesamorelin is FDA-approved; for the rest, IGF-1 rises but outcomes stay unproven.",
          "popularity": 60,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "mk677-2yr-trial",
          "headline": "MK-677 added lean mass but not strength",
          "summary": "In a 2-year randomized trial (Annals of Internal Medicine 2008) of 65 healthy older adults, the oral ghrelin mimetic MK-677 (ibutamoren) restored GH/IGF-1 toward youthful levels and increased fat-free mass by about 1 kg, but produced no gain in muscle strength or physical function, and it raised fasting glucose and reduced insulin sensitivity. MK-677 is investigational and has never been FDA-approved.",
          "category": "Trial results",
          "compounds": ["MK-677"],
          "sources": [
            {"name": "Ann Intern Med 2008 (Nass et al.)", "url": "https://doi.org/10.7326/0003-4819-149-9-200811040-00003", "kind": "journal"},
            {"name": "PubMed 18981485", "url": "https://pubmed.ncbi.nlm.nih.gov/18981485/", "kind": "journal"}
          ],
          "publishedAt": "2008-11-04T00:00:00Z",
          "teaser": "2-year trial: MK-677 added lean mass but no strength gain, and worsened glucose.",
          "popularity": 58,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "nad-nr-trial-2018",
          "headline": "NAD+ booster raised levels but benefits unproven",
          "summary": "In a randomized crossover trial (Nature Communications 2018), the NAD+ precursor nicotinamide riboside was well tolerated over 6 weeks in healthy middle-aged and older adults and raised blood NAD+ levels, with only suggestive signals for lower blood pressure. The study was small and the authors called for larger trials to test clinical benefit. NAD+ and its precursors are sold as supplements, not approved drugs.",
          "category": "Trial results",
          "compounds": ["NAD+"],
          "sources": [
            {"name": "Nat Commun 2018 (Martens et al.)", "url": "https://doi.org/10.1038/s41467-018-03421-7", "kind": "journal"},
            {"name": "Cell Metab 2017 (Yoshino, Baur & Imai — NMN/NR review)", "url": "https://doi.org/10.1016/j.cmet.2017.11.002", "kind": "journal"}
          ],
          "publishedAt": "2018-03-29T00:00:00Z",
          "teaser": "NR supplementation raised NAD+ and was well tolerated — clinical benefit still unproven.",
          "popularity": 56,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "cjc1295-pharmacology-2006",
          "headline": "CJC-1295 raised IGF-1 for weeks in early study",
          "summary": "In early dose-ranging studies in healthy adults (JCEM 2006), the long-acting GHRH analog CJC-1295 (the DAC form) raised growth hormone and IGF-1 dose-dependently, with IGF-1 staying above baseline for up to about four weeks after repeat dosing. This was an early pharmacology and safety study, not an efficacy trial, and CJC-1295 has never been FDA-approved.",
          "category": "Trial results",
          "compounds": ["CJC-1295 (DAC)"],
          "sources": [
            {"name": "JCEM 2006 (Teichman et al.)", "url": "https://doi.org/10.1210/jc.2005-1536", "kind": "journal"},
            {"name": "PubMed 16352683", "url": "https://pubmed.ncbi.nlm.nih.gov/16352683/", "kind": "journal"}
          ],
          "publishedAt": "2006-03-01T00:00:00Z",
          "teaser": "Early study: CJC-1295 (DAC) sustained IGF-1 for weeks — pharmacology only, never approved.",
          "popularity": 54,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "ghkcu-topical-vs-injectable",
          "headline": "GHK-Cu has topical data, no injectable evidence",
          "summary": "The copper tripeptide GHK-Cu has documented evidence as a topical skincare ingredient — controlled studies report improved skin firmness and reduced fine lines, plus wound-healing activity. That evidence is for topical use; there is no comparable published human trial evidence for injected GHK-Cu, which is unstudied for safety or efficacy by that route. Some of the topical literature comes from authors with a commercial skincare interest.",
          "category": "Safety",
          "compounds": ["GHK-Cu (injectable)"],
          "sources": [
            {"name": "J Biomater Sci Polym Ed 2008 (Pickart)", "url": "https://doi.org/10.1163/156856208784909435", "kind": "journal"},
            {"name": "Oxid Med Cell Longev 2012 (Pickart et al.)", "url": "https://doi.org/10.1155/2012/324832", "kind": "journal"}
          ],
          "publishedAt": "2012-05-10T00:00:00Z",
          "teaser": "GHK-Cu has real topical skin data; injectable use has no published human evidence.",
          "popularity": 52,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "aod9604-failed-program",
          "headline": "AOD-9604's obesity drug program failed",
          "summary": "AOD-9604, a synthetic fragment of human growth hormone, was developed as an anti-obesity drug and reached Phase 2 trials in the early 2000s, but the program was discontinued after it failed to show meaningful weight loss over placebo. No positive pivotal weight-loss trial is published, and the compound has since turned up in seized unlicensed peptide products. AOD-9604 is not an approved drug.",
          "category": "New compound",
          "compounds": ["AOD-9604"],
          "sources": [
            {"name": "Curr Opin Investig Drugs 2004 (Wilding — AOD-9604 review)", "url": "https://pubmed.ncbi.nlm.nih.gov/15134286/", "kind": "journal"},
            {"name": "Drug Test Anal 2014 (Vanhee et al. — seized products)", "url": "https://doi.org/10.1002/dta.1687", "kind": "journal"}
          ],
          "publishedAt": "2004-04-01T00:00:00Z",
          "teaser": "AOD-9604's obesity trials failed; it is not approved and is now sold as a supplement.",
          "popularity": 50,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "motsc-preclinical",
          "headline": "MOTS-c shows promise in animals, not in people",
          "summary": "MOTS-c is a mitochondrial-derived peptide (identified in 2015) that improves glucose metabolism and shows metabolic and exercise-related effects in cell and rodent studies. Reviews describe potential for obesity, insulin resistance and aging but note little clinical use and no established human protocol. The evidence is preclinical and early, and it is not an approved therapy.",
          "category": "New compound",
          "compounds": ["MOTS-c"],
          "sources": [
            {"name": "Free Radic Biol Med 2016 (Lee, Kim & Cohen — review)", "url": "https://doi.org/10.1016/j.freeradbiomed.2016.05.015", "kind": "journal"},
            {"name": "Front Endocrinol 2023 (Zheng et al. — review)", "url": "https://doi.org/10.3389/fendo.2023.1120533", "kind": "journal"}
          ],
          "publishedAt": "2023-01-25T00:00:00Z",
          "teaser": "MOTS-c shows metabolic effects in animals; human clinical evidence is essentially absent.",
          "popularity": 48,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "epithalon-thin-evidence",
          "headline": "Epithalon's anti-aging claims rest on thin data",
          "summary": "Epithalon (Epitalon), a synthetic pineal-derived tetrapeptide, has been studied almost exclusively by one Russian research group, which reports lifespan and geroprotective effects in animals and small human studies. This work is largely single-source, often older and small, and has not been independently replicated in modern randomized trials. Epithalon is not an approved drug and its human evidence base is weak.",
          "category": "General",
          "compounds": ["Epithalon"],
          "sources": [
            {"name": "Neuro Endocrinol Lett 2002 (Khavinson — Peptides and Ageing)", "url": "https://pubmed.ncbi.nlm.nih.gov/12374906/", "kind": "journal"},
            {"name": "Neuro Endocrinol Lett 2002 (Khavinson et al. — retinitis pigmentosa)", "url": "https://pubmed.ncbi.nlm.nih.gov/12195242/", "kind": "journal"}
          ],
          "publishedAt": "2002-08-01T00:00:00Z",
          "teaser": "Epithalon's anti-aging claims come almost entirely from one group; evidence is thin.",
          "popularity": 46,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "reta-masld-liver-fat-2024",
          "headline": "Retatrutide reduced liver fat in Phase 2a study",
          "summary": "In a Phase 2a substudy (Nature Medicine 2024) of 98 adults in the retatrutide obesity program, 48 weeks of the triple GIP/GLP-1/glucagon agonist reduced MRI-measured liver fat by roughly 43–82% across doses versus a slight increase on placebo, and most people on the higher doses reached a normal liver-fat level. Retatrutide is investigational and not FDA-approved; these are mid-stage results in metabolic dysfunction-associated steatotic liver disease (MASLD), pending Phase 3.",
          "category": "Trial results",
          "compounds": ["Retatrutide"],
          "sources": [
            {"name": "Nature Medicine 2024 (Sanyal et al., retatrutide Phase 2a MASLD)", "url": "https://doi.org/10.1038/s41591-024-03018-2", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT04881760", "url": "https://clinicaltrials.gov/study/NCT04881760", "kind": "trial"}
          ],
          "publishedAt": "2024-06-10T00:00:00Z",
          "teaser": "Phase 2a substudy: retatrutide cut liver fat up to ~82% vs placebo. Investigational.",
          "popularity": 77,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "reta-triumph-phase3-2025",
          "headline": "Retatrutide's Phase 3 TRIUMPH program is underway",
          "summary": "Eli Lilly's Phase 3 TRIUMPH program is testing retatrutide across registrational trials in more than 5,800 participants — spanning obesity with sleep apnea and knee osteoarthritis, plus a cardiovascular-kidney outcomes trial — with the program design published in 2025. No Phase 3 weight-loss topline is reported in that source. Retatrutide remains investigational and is not FDA-approved.",
          "category": "General",
          "compounds": ["Retatrutide"],
          "sources": [
            {"name": "Diabetes Obes Metab 2025 (TRIUMPH program design)", "url": "https://doi.org/10.1111/dom.70209", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT06383390 (TRIUMPH-Outcomes)", "url": "https://clinicaltrials.gov/study/NCT06383390", "kind": "trial"}
          ],
          "publishedAt": "2025-10-15T00:00:00Z",
          "teaser": "Late-stage TRIUMPH trials are testing retatrutide in 5,800+ people. No topline yet.",
          "popularity": 74,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "tesamorelin-liver-fat-2014",
          "headline": "Tesamorelin reduced liver fat in a small HIV trial",
          "summary": "In a 6-month randomized trial of 50 people with HIV (JAMA 2014), the GHRH analog tesamorelin significantly reduced liver fat and visceral fat versus placebo, though the authors called it a preliminary study and noted a transient early rise in fasting glucose. Liver-fat use is off-label and investigational — tesamorelin (Egrifta) is FDA-approved only for excess abdominal fat in HIV-associated lipodystrophy.",
          "category": "Trial results",
          "compounds": ["Tesamorelin"],
          "sources": [
            {"name": "JAMA 2014 (Stanley et al.)", "url": "https://doi.org/10.1001/jama.2014.8334", "kind": "journal"},
            {"name": "PubMed 25038357", "url": "https://pubmed.ncbi.nlm.nih.gov/25038357/", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT01263717", "url": "https://clinicaltrials.gov/study/NCT01263717", "kind": "trial"}
          ],
          "publishedAt": "2014-07-23T00:00:00Z",
          "teaser": "Small HIV trial: tesamorelin lowered liver fat and visceral fat over 6 months.",
          "popularity": 63,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "tesamorelin-cognition-2012",
          "headline": "GHRH analog showed a cognitive signal in 2012 trial",
          "summary": "In a 20-week randomized trial of 152 older adults (Archives of Neurology 2012), the GHRH analog tesamorelin produced a modest favorable effect on cognition — driven mainly by executive function — in both healthy adults and those with mild cognitive impairment. The effect was small and short-term, the authors called for longer studies, and this cognitive use is investigational and not FDA-approved.",
          "category": "Trial results",
          "compounds": ["Tesamorelin"],
          "sources": [
            {"name": "Arch Neurol 2012 (Baker et al.)", "url": "https://doi.org/10.1001/archneurol.2012.1970", "kind": "journal"},
            {"name": "PubMed 22869065", "url": "https://pubmed.ncbi.nlm.nih.gov/22869065/", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT00257712", "url": "https://clinicaltrials.gov/study/NCT00257712", "kind": "trial"}
          ],
          "publishedAt": "2012-11-01T00:00:00Z",
          "teaser": "20-week trial hinted at an executive-function benefit from GHRH — modest, preliminary.",
          "popularity": 55,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "healing-blends-no-trials",
          "headline": "Recovery blends (Wolverine, GLOW) lack human trials",
          "summary": "Popular compounded recovery blends — Wolverine (BPC-157 + TB-500) and GLOW (which adds GHK-Cu) — have never been tested as combinations in any registered clinical trial. Their individual components are mostly preclinical: BPC-157's human data are minimal, TB-500 (a thymosin beta-4 fragment) is largely animal-stage, and GHK-Cu is best studied as a topical skincare ingredient. None are FDA-approved, and combining unapproved peptides adds unquantified interaction and safety risk.",
          "category": "General",
          "compounds": ["BPC-157", "TB-500", "GHK-Cu (injectable)"],
          "sources": [
            {"name": "Pharmaceutics 2026 (MDPI, BPC-157 review; doi:10.3390/pharmaceutics18050625)", "url": "https://doi.org/10.3390/pharmaceutics18050625", "kind": "journal"},
            {"name": "Oxid Med Cell Longev 2012 (Pickart et al., GHK-Cu)", "url": "https://doi.org/10.1155/2012/324832", "kind": "journal"}
          ],
          "publishedAt": "2026-05-22T00:00:00Z",
          "teaser": "Wolverine (BPC-157+TB-500) and GLOW blends have no combination trials in humans.",
          "popularity": 61,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "cjc-ipamorelin-combo-evidence",
          "headline": "CJC-1295 + ipamorelin: popular combo, thin human data",
          "summary": "CJC-1295 and ipamorelin are often stacked to raise growth hormone, but the human evidence is limited. CJC-1295 (the DAC form) raised GH and IGF-1 for days in an early pharmacology study (JCEM 2006), while ipamorelin — a selective GH secretagogue — has little published human data and no efficacy trials for body composition or anti-aging. Neither is FDA-approved, and the specific CJC-1295 + ipamorelin combination has not been tested in controlled human trials.",
          "category": "General",
          "compounds": ["CJC-1295 (DAC)", "CJC-1295 (no DAC)", "Ipamorelin"],
          "sources": [
            {"name": "JCEM 2006 (Teichman et al., CJC-1295)", "url": "https://doi.org/10.1210/jc.2005-1536", "kind": "journal"},
            {"name": "PubMed 16352683", "url": "https://pubmed.ncbi.nlm.nih.gov/16352683/", "kind": "journal"}
          ],
          "publishedAt": "2006-03-01T00:00:00Z",
          "teaser": "The CJC-1295 + ipamorelin stack is popular but has no controlled human combo data.",
          "popularity": 57,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "motsc-exercise-2021",
          "headline": "MOTS-c acts like an exercise-linked mitochondrial peptide",
          "summary": "Reviews describe MOTS-c, a mitochondria-derived peptide, as exercise-responsive: intense exercise can raise MOTS-c in human muscle and blood, and in mice MOTS-c improves exercise capacity and insulin sensitivity — an 'exercise-mimetic' or mitohormesis role. The human data are limited and largely associative, and there is no approved MOTS-c therapy; the evidence remains early and preclinical.",
          "category": "New compound",
          "compounds": ["MOTS-c"],
          "sources": [
            {"name": "BBA General Subjects 2021 (Woodhead & Merry, review)", "url": "https://doi.org/10.1016/j.bbagen.2021.130011", "kind": "journal"},
            {"name": "PubMed 34520826", "url": "https://pubmed.ncbi.nlm.nih.gov/34520826/", "kind": "journal"}
          ],
          "publishedAt": "2021-12-01T00:00:00Z",
          "teaser": "MOTS-c behaves like an exercise-responsive mitochondrial peptide — still preclinical.",
          "popularity": 47,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "nmn-insulin-sensitivity-2021",
          "headline": "NMN improved muscle insulin sensitivity in a trial",
          "summary": "In a 10-week randomized, placebo-controlled trial (Science 2021) in postmenopausal women with prediabetes and overweight or obesity, the NAD+ precursor nicotinamide mononucleotide (NMN) increased insulin-stimulated glucose disposal and muscle insulin signaling versus placebo. It was a small, single-center study that did not change body weight or liver fat, and other NMN trials have been mixed; NMN is a dietary supplement, not an approved drug.",
          "category": "Trial results",
          "compounds": ["NAD+"],
          "sources": [
            {"name": "Science 2021 (Yoshino et al., NMN RCT)", "url": "https://doi.org/10.1126/science.abe9985", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT03151239", "url": "https://clinicaltrials.gov/study/NCT03151239", "kind": "trial"}
          ],
          "publishedAt": "2021-04-22T00:00:00Z",
          "teaser": "10-week RCT: NMN improved muscle insulin sensitivity in prediabetic women.",
          "popularity": 57,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "glutathione-iv-skin-safety",
          "headline": "IV glutathione for skin whitening: unapproved, risky",
          "summary": "Intravenous and injectable glutathione is widely marketed for skin lightening, but no regulator has approved it for that use and no published clinical trials show it safely and durably lightens skin. The Philippine FDA has formally warned against high-dose IV glutathione for whitening, and the US FDA has flagged contamination risks in compounded glutathione injectables; reported harms include serious allergic reactions and possible liver and kidney effects.",
          "category": "Safety",
          "compounds": ["Glutathione"],
          "sources": [
            {"name": "Philippine FDA Advisory 2019-182 (IV glutathione for skin whitening)", "url": "https://www.fda.gov.ph/fda-advisory-no-2019-182-unsafe-use-of-glutathione-as-skin-lightening-agent/", "kind": "regulatory"},
            {"name": "U.S. FDA — compounded glutathione injectables", "url": "https://www.fda.gov/drugs/human-drug-compounding/fda-highlights-concerns-using-dietary-ingredient-glutathione-compound-sterile-injectables", "kind": "regulatory"},
            {"name": "Cureus 2025 (glutathione review)", "url": "https://doi.org/10.7759/cureus.78045", "kind": "journal"}
          ],
          "publishedAt": "2025-01-27T00:00:00Z",
          "teaser": "Injectable glutathione for lighter skin is unapproved and carries safety warnings.",
          "popularity": 53,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "glutathione-oral-rct-2015",
          "headline": "Oral glutathione raised body stores in a 6-month RCT",
          "summary": "In a 6-month randomized, placebo-controlled trial of 54 healthy adults (European Journal of Nutrition 2015), daily oral glutathione (250 or 1,000 mg) significantly raised glutathione levels in blood and tissues versus placebo, with levels returning to baseline after a one-month washout. The endpoints were body stores and oxidative-stress markers, not a specific clinical or skin benefit; glutathione is a dietary supplement, not an approved drug.",
          "category": "Trial results",
          "compounds": ["Glutathione"],
          "sources": [
            {"name": "Eur J Nutr 2015 (Richie et al., oral glutathione RCT)", "url": "https://doi.org/10.1007/s00394-014-0706-z", "kind": "journal"},
            {"name": "PubMed 24791752", "url": "https://pubmed.ncbi.nlm.nih.gov/24791752/", "kind": "journal"}
          ],
          "publishedAt": "2015-04-01T00:00:00Z",
          "teaser": "Small 6-month RCT: oral glutathione raised body glutathione stores vs placebo.",
          "popularity": 49,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        },
        {
          "id": "reta-prediabetes-reversion-2023",
          "headline": "Retatrutide reversed prediabetes for most in Phase 2",
          "summary": "In the Phase 2 obesity trial (NEJM 2023), among the roughly one in three participants who had prediabetes at baseline, 72% of those on retatrutide returned to normal blood sugar (HbA1c below 5.7%) by 48 weeks, versus 22% on placebo. This was an exploratory finding pooled across doses — not the trial's primary endpoint, and not statistically powered for this outcome. Retatrutide is investigational and not FDA-approved.",
          "category": "Trial results",
          "compounds": ["Retatrutide"],
          "sources": [
            {"name": "NEJM 2023 (Jastreboff et al., retatrutide Phase 2)", "url": "https://doi.org/10.1056/NEJMoa2301972", "kind": "journal"},
            {"name": "PubMed 37366315", "url": "https://pubmed.ncbi.nlm.nih.gov/37366315/", "kind": "journal"},
            {"name": "ClinicalTrials.gov NCT04881760", "url": "https://clinicaltrials.gov/study/NCT04881760", "kind": "trial"}
          ],
          "publishedAt": "2023-06-26T00:00:00Z",
          "teaser": "Phase 2: 72% of prediabetic participants normalized blood sugar on retatrutide vs 22% on placebo.",
          "popularity": 76,
          "isMajorUpdate": false,
          "disclaimer": "Neutral informational summary. Not medical advice. Read the linked sources and consult a clinician."
        }
      ]
    }
    """#

    /// Decodes the bundled sample feed. Throws if the fixture ever drifts from the model.
    static func decodeSample() throws -> NewsFeed {
        try JSONDecoder().decode(NewsFeed.self, from: Data(sampleJSON.utf8))
    }
}
